# Generated by Django 5.2.2 on 2025-09-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10, unique=True, verbose_name='รหัสวิชา')),
                ('subject_name', models.CharField(max_length=200, verbose_name='ชื่อวิชา')),
                ('instructor_name', models.CharField(max_length=100, verbose_name='ชื่อผู้สอน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
            ],
            options={
                'verbose_name': 'วิชา',
                'verbose_name_plural': 'วิชา',
                'ordering': ['subject_code'],
            },
        ),
    ]
